BAUHINIA_Ecommerce/Controllers/DashboardController.cs
using AspNetCoreHero.ToastNotification.Abstractions;
using Ecommerce.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace BAUHINIA_Ecommerce.Controllers
{
    public class DashboardController : Controller
    {
        IMemoryCache memoryCache;
        private UserM Usr = new UserM();
        private readonly INotyfService _notyf;

        public DashboardController(IMemoryCache memoryCache, INotyfService notyf)
        {
            this.memoryCache = memoryCache;
            Usr = memoryCache.Get("LoggedUser") as UserM;
            _notyf = notyf;
        }
        public IActionResult Index()
        {
            if (Usr == null || Usr.UserId == 0)
            {
                return RedirectToAction("Index", "Login");
            }
            return View();
        }
    }
}

BAUHINIA_Ecommerce/ViewComponents/DashboardNavViewComponent.cs
using Ecommerce.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace BAUHINIA_Ecommerce.ViewComponents
{
    [ViewComponent(Name = "DashboardNav")]
    public class DashboardNavViewComponent : ViewComponent
    {
        IMemoryCache memoryCache;
        public DashboardNavViewComponent(IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache;
        }

        public IViewComponentResult Invoke()
        {
            UserM Usr = new UserM();
            Usr = memoryCache.Get("LoggedUser") as UserM;

            return View(Usr);
        }

    }
}

BAUHINIA_Ecommerce/ViewComponents/DashboardSidebarViewComponent.cs
using Ecommerce.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;

namespace BAUHINIA_Ecommerce.ViewComponents
{
    [ViewComponent(Name = "DashboardSidebar")]
    public class DashboardSidebarViewComponent : ViewComponent
    {
        IMemoryCache memoryCache;
        public DashboardSidebarViewComponent(IMemoryCache memoryCache)
        {
            this.memoryCache = memoryCache; ;

        }

        public IViewComponentResult Invoke()
        {
            UserM Usr = new UserM();
            Usr = memoryCache.Get("LoggedUser") as UserM;

            return View(Usr);
        }



    }
}

BAUHINIA_Ecommerce/Views/Shared/_LayoutDashboard.cshtml
<!DOCTYPE html>

<html lang="en"
      class="light-style layout-menu-fixed"
      dir="ltr"
      data-theme="theme-default"
      data-template="vertical-menu-template-free">
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"] | BAUHINIA </title>

    <link rel="icon" type="image/x-icon" href="~/assets/be/img/favicon/faviconb.ico" />

    @*<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" />*@
    @*<link href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" rel="stylesheet" />*@
    <link href="~/css/jquery.dataTables.min.css" rel="stylesheet" />

    <!-- Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Public+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet" />

    <!-- Icons. Uncomment required icon fonts -->
    <link rel="stylesheet" href="~/assets/be/vendor/fonts/boxicons.css" />

    <!-- Core CSS -->
    <link rel="stylesheet" href="~/assets/be/vendor/css/core.css" class="template-customizer-core-css" />
    <link rel="stylesheet" href="~/assets/be/vendor/css/theme-default.css" class="template-customizer-theme-css" />
    <link rel="stylesheet" href="~/assets/be/css/demo.css" />

    <!-- Vendors CSS -->
    <link rel="stylesheet" href="~/assets/be/vendor/libs/perfect-scrollbar/perfect-scrollbar.css" />

    <link rel="stylesheet" href="~/assets/be/vendor/libs/apex-charts/apex-charts.css" />

    <!-- Page CSS -->
    <!-- Helpers -->
    <script src="~/assets/be/vendor/js/helpers.js"></script>

    <script src="~/assets/be/js/config.js"></script>



    @*<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/css/dataTables.bootstrap.min.css'>*@
    <link rel="stylesheet" href="~/css/dataTables.bootstrap.min.css" asp-append-version="true" />
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,500" rel="stylesheet" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/jquery.dataTables.min.css" asp-append-version="true">

    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

</head>
<body>

    <!-- Layout wrapper -->
    <div class="layout-wrapper layout-content-navbar">
        <div class="layout-container">
            <!-- Menu -->

            <aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">
                <div class="app-brand demo" style="padding-left:1rem!important;">
                    <a asp-area="" asp-action="Index" asp-controller="Dashboard" class="app-brand-link">

                        <span class="app-brand-text demo menu-text fw-bolder ms-2">
                            <img class="app-brand-logo demo" src="~/assets/be/img/logo/logo.png" style="max-width:200px;" />

                        </span>
                    </a>

                    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto d-block d-xl-none">
                        <i class="bx bx-chevron-left bx-sm align-middle"></i>
                    </a>
                </div>

                <div class="menu-inner-shadow"></div>

                <ul class="menu-inner py-1">
                    <!-- Dashboard -->
                    <li class="menu-item active">
                        <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="menu-link">
                            <i class="menu-icon tf-icons bx bx-home-circle"></i>
                            <div data-i18n="Analytics">Dashboard</div>
                        </a>
                    </li>


                    <li class="menu-header small text-uppercase">
                        <span class="menu-header-text">Pages</span>
                    </li>


                    @await Component.InvokeAsync("DashboardSidebar")


                </ul>
            </aside>
            <!-- / Menu -->
            <!-- Layout container -->
            <div class="layout-page">


                <!-- Navbar -->

                <nav class="layout-navbar container-xxl navbar navbar-expand-xl navbar-detached align-items-center bg-navbar-theme"
                     id="layout-navbar">
                    <div class="layout-menu-toggle navbar-nav align-items-xl-center me-3 me-xl-0 d-xl-none">
                        <a class="nav-item nav-link px-0 me-xl-4" href="javascript:void(0);">
                            <i class="bx bx-menu bx-sm"></i>
                        </a>
                    </div>

                    <div class="navbar-nav-right d-flex align-items-center" id="navbar-collapse">

                        <!-- Search -->
                        <div class="navbar-nav align-items-center">
                            <div class="nav-item d-flex align-items-center">
                                <i class="bx bx-search fs-4 lh-0"></i>
                                <input type="text"
                                       class="form-control border-0 shadow-none"
                                       placeholder="Search..."
                                       aria-label="Search..." />
                            </div>
                        </div>
                        <!-- /Search -->
                        <!-- /Search -->
                        @await Component.InvokeAsync("DashboardNav")
                    </div>
                </nav>

                <!-- / Navbar -->
                @RenderBody()

            </div>

        </div>


        <!-- Overlay -->
        <div class="layout-overlay layout-menu-toggle"></div>

    </div>



    <!-- Core JS -->
    <!-- build:js assets/vendor/js/core.js -->
    <script src="~/assets/be/vendor/libs/jquery/jquery.js"></script>
    <script src="~/assets/be/vendor/libs/popper/popper.js"></script>
    <script src="~/assets/be/vendor/js/bootstrap.js"></script>
    <script src="~/assets/be/vendor/libs/perfect-scrollbar/perfect-scrollbar.js"></script>

    <script src="~/assets/be/vendor/js/menu.js"></script>
    <!-- endbuild -->
    <!-- Vendors JS -->
    <script src="~/assets/be/vendor/libs/apex-charts/apexcharts.js"></script>

    <!-- Main JS -->
    <script src="~/assets/be/js/main.js"></script>

    <!-- Page JS -->
    <script src="~/assets/be/js/dashboards-analytics.js"></script>

    <!-- Place this tag in your head or just before your close body tag. -->
    <script async defer src="https://buttons.github.io/buttons.js"></script>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/jquery.dataTables.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/datatables/1.10.12/js/dataTables.bootstrap.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.0/moment.min.js'></script>
    <script language="javascript" type="text/javascript" src="~/js/function.js"></script>
    @*
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>*@

    @await Component.InvokeAsync("Notyf")

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

BAUHINIA_Ecommerce/Views/Shared/_ShoppingCart.cshtml
<div class="flex-c-m h-full p-l-18 p-r-25 bor5">

    <a asp-area="" asp-controller="Customer" asp-action="Login">
        <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11">

            <span class="stext-109 cl4" style="font-size:16px">
                Login
            </span>
        </div>
    </a>
</div>



<div class="flex-c-m h-full p-l-18 p-r-25 bor5">

    <a asp-area="" asp-controller="Home" asp-action="ShoppingCart">
        <div class="icon-header-item cl2 hov-cl1 trans-04 p-lr-11 ">
            <i class="zmdi zmdi-shopping-cart"></i>
        </div>
    </a>
</div>